/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FireeyeToggleSwitch {
        /**
          * Background of toggle when in active state
         */
        "backgroundActive": string;
        /**
          * Background of toggle when in in-active state
         */
        "backgroundInActive": string;
        /**
          * The value of toggle  switch
         */
        "checked": boolean;
        /**
          * height of toggle switch
         */
        "height": string;
        /**
          * if yes toggle is rounded else square
         */
        "isRounded": boolean;
        /**
          * width of toggle switch
         */
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFireeyeToggleSwitchElement extends Components.FireeyeToggleSwitch, HTMLStencilElement {
    }
    var HTMLFireeyeToggleSwitchElement: {
        prototype: HTMLFireeyeToggleSwitchElement;
        new (): HTMLFireeyeToggleSwitchElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fireeye-toggle-switch": HTMLFireeyeToggleSwitchElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FireeyeToggleSwitch {
        /**
          * Background of toggle when in active state
         */
        "backgroundActive"?: string;
        /**
          * Background of toggle when in in-active state
         */
        "backgroundInActive"?: string;
        /**
          * The value of toggle  switch
         */
        "checked"?: boolean;
        /**
          * height of toggle switch
         */
        "height"?: string;
        /**
          * if yes toggle is rounded else square
         */
        "isRounded"?: boolean;
        /**
          * Click event
         */
        "onToggleClick"?: (event: CustomEvent<any>) => void;
        /**
          * width of toggle switch
         */
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fireeye-toggle-switch": FireeyeToggleSwitch;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fireeye-toggle-switch": LocalJSX.FireeyeToggleSwitch & JSXBase.HTMLAttributes<HTMLFireeyeToggleSwitchElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
