/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FireeyeToggleButton {
        /**
          * Background of toggle when in active state
         */
        "backgroundActive": string;
        /**
          * Background of toggle when in in-active state
         */
        "backgroundInActive": string;
        /**
          * height of toggle button
         */
        "height": string;
        /**
          * if yes toggle is rounded else square
         */
        "isRounded": boolean;
        /**
          * The value of toggle  button
         */
        "value": boolean;
        /**
          * width of toggle button
         */
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFireeyeToggleButtonElement extends Components.FireeyeToggleButton, HTMLStencilElement {
    }
    var HTMLFireeyeToggleButtonElement: {
        prototype: HTMLFireeyeToggleButtonElement;
        new (): HTMLFireeyeToggleButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fireeye-toggle-button": HTMLFireeyeToggleButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FireeyeToggleButton {
        /**
          * Background of toggle when in active state
         */
        "backgroundActive"?: string;
        /**
          * Background of toggle when in in-active state
         */
        "backgroundInActive"?: string;
        /**
          * height of toggle button
         */
        "height"?: string;
        /**
          * if yes toggle is rounded else square
         */
        "isRounded"?: boolean;
        /**
          * Click event
         */
        "onToggleClick"?: (event: CustomEvent<any>) => void;
        /**
          * The value of toggle  button
         */
        "value"?: boolean;
        /**
          * width of toggle button
         */
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fireeye-toggle-button": FireeyeToggleButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fireeye-toggle-button": LocalJSX.FireeyeToggleButton & JSXBase.HTMLAttributes<HTMLFireeyeToggleButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
